### ISSUE TITLE
Setting up CI

### ISSUE THREAD

**Issue by vchuravy** [flux-framework/FluxRM.jl#2]
@SteVwonder could I ask for your help with setting up CI? I think you mentioned that there were docker images available?

A typical Github Actions workflow for a Julia package looks like https://github.com/JuliaGPU/KernelAbstractions.jl/blob/master/.github/workflows/ci.yml and for now I am punting on having Flux be automatically installed due to https://github.com/flux-framework/flux-core/issues/3508

**Comment by SteVwonder** [comment]
> I think you mentioned that there were docker images available?

Yep.  We manage the `fluxrm` org on docker hub.  So `fluxrm/flux-core` is the image/docker hub "repo" you probably want.  For every merge to master, the flux-core CI pushes the following tags for that "repo":

- bionic
- focal
- latest (same as bionic)
- centos8
- centos7
- fedora33

FWIW, for the rust bindings (https://github.com/flux-framework/flux-rs), we just test on the more recent OSes: `focal` and `centos8`.

> could I ask for your help with setting up CI?

Sure.  I'll admit my experience with Github Actions is limited to the rust bindings.  I know Github Actions has support for containers in the workflow syntax (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer).  I'm tempted to say you can just copy-and-paste from the other Julia CI yaml files you are used to using, stick `container: {image: fluxrm/flux-core:latest}` in the `job`, and all of the steps and actions will just run within that container.

I **think** I tried that with the rust bindings and had issues; probably due to "If you have steps that use both script and container actions, the container actions will run as sibling containers on the same network with the same volume mounts." Ultimately, I ended up just modeling the rust binding CI after flux-sched, which builds a new docker image using the flux-core image as a base and then builds/tests the rust bindings within that new image.  For reference:

- script that sets up the docker image and runs the container:
https://github.com/flux-framework/flux-rs/blob/master/src/test/docker-run-checks.sh
- "CI script" that is run within the container: https://github.com/flux-framework/flux-rs/blob/master/src/test/ci_run.sh

Any thoughts? Any experience with running actions inside of container?

**Comment by vchuravy** [comment]
> Any thoughts? Any experience with running actions inside of container?

After #3  I would say that "feature" is just thoroughly not working.

**Comment by vchuravy** [comment]
Ok @giordano and I got something working now I just need to start writing tests and code ;)

**Comment by vchuravy** [comment]
For the record the issue was that on GHA all files were owned by `root` and that propagated into the container were we were trying to run things as `fluxuser`.
